// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

var JsError = /* @__PURE__ */Caml_exceptions.create("Promise.JsError");

function $$catch(promise, callback) {
  return promise.catch(function (err) {
              return Curry._1(callback, Caml_exceptions.caml_is_extension(err) ? err : ({
                              RE_EXN_ID: JsError,
                              _1: err
                            }));
            });
}

function allSettled(arr) {
  return Promise.allSettled(arr).then(function (values) {
              return values.map(function (val) {
                          var match = val.status;
                          if (match === "rejected") {
                            return {
                                    TAG: /* Rejected */1,
                                    _0: val.reason
                                  };
                          } else {
                            return {
                                    TAG: /* Fulfilled */0,
                                    _0: val.value
                                  };
                          }
                        });
            });
}

exports.JsError = JsError;
exports.$$catch = $$catch;
exports.allSettled = allSettled;
/* No side effect */
